### ISSUE TITLE
containers using this as base image have /sbin/init missing

### ISSUE THREAD

**Issue by NicTanghe** [eniocarboni/docker-ubuntu-systemd#8]
Hello containers that are created from this baseimage have /sbin/init missing.
I cant fathom why.

```dockerfile
ENV DEBIAN_FRONTEND=noninteractive

# Update and install required packages
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    iputils-ping \
    netcat \
    #inetutils-telnet \
    inetutils-ftp \
    procps \
    sudo && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install additional required libraries for Houdini
RUN apt-get update && \
    apt-get install -y \
    libglu1 \
    libsm6 \
    bc \
    wget \
    libnss3 \
    libxcomposite1 \
    libxrender1 \
    libxrandr2 \
    libfontconfig1 \
    libxcursor1 \
    libxi6 \
    libxtst6 \
    libxkbcommon0 \
    libxss1 \
    libpci3 \
    ffmpeg \


    systemd \
    systemd-cron \

    libxdamage1  \
    
    libasound2 && \


    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Copy Houdini tar.gz file into the container (ensure it's in the same directory as the Dockerfile)
COPY houdini-20.5.445-linux_x86_64_gcc11.2.tar.gz /tmp/

# Extract Houdini tar.gz file
RUN tar -xzvf /tmp/houdini-20.5.445-linux_x86_64_gcc11.2.tar.gz -C /tmp/ && \
    rm /tmp/houdini-20.5.445-linux_x86_64_gcc11.2.tar.gz

# Expose ports in the Dockerfile (this is just for documentation and doesn't actually bind them)
EXPOSE 5000 5001 1714 1715

# Set working directory
WORKDIR /tmp/houdini-20.5.445-linux_x86_64_gcc11.2


VOLUME ["/sys/fs/cgroup", "/tmp", "/run"]
CMD ["/lib/systemd/systemd"]
```

```yml
version: '3.8'

services:
  ubuntu_service:
    image: 192.168.178.82:5004/sidefx-portal:latest
    container_name: sidefx-portal
    mac_address: 02:42:ac:11:00:02
    hostname: UBUNTU-FX-server-01
    privileged: true
    #cgroupns_mode: host
    command: /sbin/init
    ports:
      - "5000:5000"
      - "5001:5001"
      - "1714:1714"
      - "1715:1715"
    volumes:
      - /shares/hqueue:/mnt/hqueue
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /run
      - /run/lock
    networks:
      - ubuntu_network

networks:
  ubuntu_network:
    driver: bridge
    ```
